# -*- coding: utf-8 -*-
# Hand-curated pilot corpus (24 passages) and 48 questions (matched / paraphrased).

PASSAGES = [
("photosynthesis", "Photosynthesis is the process by which green plants and some other organisms use sunlight to synthesize foods from carbon dioxide and water. The process generates oxygen as a byproduct. It takes place mainly in the leaves, within structures called chloroplasts. Photosynthesis is the primary source of energy for nearly all life on Earth."),
("eiffel_tower", "The Eiffel Tower is a wrought-iron lattice structure located on the Champ de Mars in Paris, France. It was designed by engineer Gustave Eiffel and completed in 1889 as the entrance arch for the World's Fair. Standing at 330 meters, it was the tallest man-made structure in the world until 1930."),
("great_barrier_reef", "The Great Barrier Reef is the world's largest coral reef system, located off the coast of Queensland, Australia. It stretches over 2,300 kilometers and is composed of thousands of individual reefs and hundreds of islands. The reef is home to a vast diversity of marine life but has suffered significant coral bleaching due to rising ocean temperatures."),
("marie_curie", "Marie Curie was a physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize and remains the only person to win Nobel Prizes in two different scientific fields, physics and chemistry. Her discoveries included the elements polonium and radium."),
("mount_everest", "Mount Everest is Earth's highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas. Its peak reaches 8,849 meters. The mountain straddles the border between Nepal and the Tibet Autonomous Region of China and was first summited by Edmund Hillary and Tenzing Norgay in 1953."),
("amazon_river", "The Amazon River in South America is the largest river by discharge volume of water in the world. It flows primarily through Brazil and Peru, and its basin supports the largest rainforest on the planet. The river system contains an estimated one-fifth of the world's flowing freshwater."),
("dna_double_helix", "James Watson and Francis Crick proposed the double helix structure of DNA in 1953, building on X-ray diffraction data collected by Rosalind Franklin. The discovery explained how genetic information could be replicated and passed to offspring. It is considered one of the most significant scientific discoveries of the 20th century."),
("french_revolution", "The French Revolution began in 1789 and led to the overthrow of the French monarchy. It was driven by widespread social inequality, financial crisis, and Enlightenment ideas about liberty and citizenship. The period culminated in the rise of Napoleon Bonaparte as a dominant political and military leader."),
("hamlet", "Hamlet is a tragedy written by William Shakespeare, believed to have been composed between 1599 and 1601. The play follows Prince Hamlet as he seeks revenge against his uncle for murdering his father, the King of Denmark, and seizing the throne. It is one of Shakespeare's most quoted works."),
("great_wall", "The Great Wall of China is a series of fortifications built across the historical northern borders of China to protect against invasions. Construction began as early as the 7th century BC, with the most famous sections built during the Ming Dynasty. The wall stretches for thousands of kilometers."),
("black_holes", "A black hole is a region of spacetime where gravity is so strong that nothing, not even light, can escape from it. Black holes form when massive stars collapse at the end of their life cycle. The boundary beyond which escape is impossible is called the event horizon."),
("renaissance", "The Italian Renaissance was a period of cultural rebirth spanning roughly the 14th to 17th centuries, beginning in Florence. It marked a revival of interest in classical art, literature, and learning, and produced masters such as Leonardo da Vinci and Michelangelo. The movement later spread across Europe."),
("industrial_revolution", "The Industrial Revolution was a period of major industrialization that began in Great Britain in the late 18th century. It transformed manufacturing through mechanization, steam power, and factory production. The changes led to significant urban growth and shifted economies from agrarian to industrial bases."),
("great_depression", "The Great Depression was a severe worldwide economic downturn that began in 1929, triggered by the Wall Street stock market crash. It caused massive unemployment, bank failures, and a sharp decline in industrial output across many countries. Recovery efforts included government programs such as the New Deal in the United States."),
("human_heart", "The human heart is a muscular organ that pumps blood through the circulatory system. It has four chambers: two atria and two ventricles. An adult heart beats roughly 60 to 100 times per minute at rest, circulating blood to deliver oxygen and nutrients to body tissues."),
("volcanoes", "A volcano is a rupture in the Earth's crust that allows hot magma, ash, and gases to escape from below the surface. Volcanic eruptions can be explosive or effusive depending on the magma's composition. Volcanoes often form along tectonic plate boundaries."),
("apollo_11", "Apollo 11 was the spaceflight that first landed humans on the Moon on July 20, 1969. Astronauts Neil Armstrong and Buzz Aldrin walked on the lunar surface while Michael Collins orbited above in the command module. The mission fulfilled a national goal set by President John F. Kennedy."),
("end_of_ww2", "World War II in Europe ended on May 8, 1945, when Germany signed an unconditional surrender, a day celebrated as V-E Day. The war in the Pacific concluded later that year, in September 1945, following Japan's surrender after the atomic bombings of Hiroshima and Nagasaki."),
("sahara_desert", "The Sahara is the largest hot desert in the world, covering much of North Africa. It spans an area comparable in size to the United States and experiences extremely high daytime temperatures with very low rainfall. Despite its harsh climate, it is home to nomadic populations and diverse wildlife adapted to arid conditions."),
("relativity", "Albert Einstein developed the theory of relativity, which transformed the understanding of space, time, and gravity. His 1905 special relativity introduced the equivalence of mass and energy, while general relativity in 1915 described gravity as the curvature of spacetime. Einstein won the Nobel Prize in Physics in 1921."),
("printing_press", "Johannes Gutenberg introduced the printing press with movable metal type to Europe around 1440. His invention dramatically reduced the cost of producing books and enabled the rapid spread of knowledge. The Gutenberg Bible, printed around 1455, was among the first major books produced using this technology."),
("penicillin", "Alexander Fleming discovered penicillin in 1928 when he noticed that a mold contaminating one of his bacterial cultures was killing the surrounding bacteria. This observation led to the development of the first widely used antibiotic, revolutionizing the treatment of bacterial infections and saving countless lives."),
("statue_of_liberty", "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor. It was a gift from France to the United States, dedicated in 1886, and symbolizes freedom and democracy. The statue depicts a robed female figure holding a torch and a tablet inscribed with the date of American independence."),
("jenner_vaccine", "Edward Jenner developed the world's first vaccine in 1796 by using material from cowpox lesions to protect against smallpox. His work laid the foundation for the field of immunology and eventually led to the global eradication of smallpox in 1980. Jenner is often called the father of immunology."),
]

# Each entry: (passage_id, question_text, type) where type in {"matched","paraphrased"}
QUESTIONS = [
("photosynthesis", "What is the process by which plants use sunlight to make food from carbon dioxide and water?", "matched"),
("photosynthesis", "How do green organisms convert light energy into chemical energy while releasing a gas as a side effect?", "paraphrased"),
("eiffel_tower", "Who designed the Eiffel Tower and when was it completed?", "matched"),
("eiffel_tower", "Which Parisian landmark, built as a fair entrance gate, held the record for the world's tallest built structure into the 1930s?", "paraphrased"),
("great_barrier_reef", "What is the world's largest coral reef system and where is it located?", "matched"),
("great_barrier_reef", "Which enormous underwater ecosystem near northeastern Australia has been damaged by warming seas?", "paraphrased"),
("marie_curie", "Which scientist won Nobel Prizes in physics and chemistry for research on radioactivity?", "matched"),
("marie_curie", "Who became the first female Nobel laureate and identified two new radioactive elements?", "paraphrased"),
("mount_everest", "What is the highest mountain on Earth and who first reached its summit?", "matched"),
("mount_everest", "Which Himalayan peak, the tallest above sea level, was conquered for the first time by a New Zealand climber and his Sherpa guide?", "paraphrased"),
("amazon_river", "Which river has the largest discharge volume in the world and where does it flow?", "matched"),
("amazon_river", "What South American waterway carries roughly a fifth of the planet's flowing fresh water through the world's biggest rainforest?", "paraphrased"),
("dna_double_helix", "Who proposed the double helix structure of DNA and in what year?", "matched"),
("dna_double_helix", "Which pair of scientists, using crystallography data from a colleague, worked out how hereditary material is shaped and copied?", "paraphrased"),
("french_revolution", "When did the French Revolution begin and what did it lead to?", "matched"),
("french_revolution", "What late-18th-century uprising, fueled by economic hardship and new ideas about rights, ended royal rule and paved the way for a military strongman's rise?", "paraphrased"),
("hamlet", "Who wrote the tragedy Hamlet and what is it about?", "matched"),
("hamlet", "Which Elizabethan playwright authored a story of a Danish prince avenging his father's murder by a usurping relative?", "paraphrased"),
("great_wall", "What fortifications were built to protect China's northern borders from invasion?", "matched"),
("great_wall", "Which lengthy defensive barrier, largely rebuilt under a later imperial dynasty, guarded ancient China from northern attackers?", "paraphrased"),
("black_holes", "What is a black hole and how does it form?", "matched"),
("black_holes", "What cosmic object, created by the collapse of a dying massive star, traps even light beyond a boundary called the event horizon?", "paraphrased"),
("renaissance", "What was the Italian Renaissance and where did it begin?", "matched"),
("renaissance", "Which cultural movement, starting in a Tuscan city and reviving classical learning, gave rise to artists like da Vinci and Michelangelo?", "paraphrased"),
("industrial_revolution", "Where and when did the Industrial Revolution begin?", "matched"),
("industrial_revolution", "Which nation experienced an 18th-century wave of mechanized factory production that shifted its economy away from farming?", "paraphrased"),
("great_depression", "What triggered the Great Depression and when did it begin?", "matched"),
("great_depression", "Which global economic collapse, sparked by a 1929 financial market crash, led to widespread joblessness and a U.S. government recovery program?", "paraphrased"),
("human_heart", "How many chambers does the human heart have and what does it do?", "matched"),
("human_heart", "Which four-chambered muscular organ circulates oxygen-carrying fluid throughout the body at a typical resting rate of 60 to 100 beats per minute?", "paraphrased"),
("volcanoes", "What is a volcano and where do they often form?", "matched"),
("volcanoes", "What geological opening lets molten rock and gases rise from beneath the crust, typically appearing along the edges of tectonic plates?", "paraphrased"),
("apollo_11", "Which spaceflight first landed humans on the Moon and who walked on its surface?", "matched"),
("apollo_11", "What 1969 NASA mission fulfilled a presidential goal by putting two astronauts on the lunar surface while a third orbited overhead?", "paraphrased"),
("end_of_ww2", "When did World War II end in Europe and in the Pacific?", "matched"),
("end_of_ww2", "After the atomic bombing of two Japanese cities, when did the Pacific conflict conclude, following Germany's earlier surrender that spring?", "paraphrased"),
("sahara_desert", "What is the largest hot desert in the world and where is it located?", "matched"),
("sahara_desert", "Which vast, sparsely watered North African expanse, roughly the size of the United States, supports nomadic peoples despite scorching daytime heat?", "paraphrased"),
("relativity", "Who developed the theory of relativity and what did it describe?", "matched"),
("relativity", "Which physicist, later honored with a 1921 Nobel Prize, reshaped ideas about space and time and explained gravity as bent spacetime?", "paraphrased"),
("printing_press", "Who introduced the printing press with movable type and around what year?", "matched"),
("printing_press", "Which 15th-century German inventor's device made books far cheaper to produce, first demonstrated with a famous printed scripture?", "paraphrased"),
("penicillin", "Who discovered penicillin and how did the discovery happen?", "matched"),
("penicillin", "Which scientist noticed a stray mold destroying bacteria in his lab dish, leading to the first mass-produced antibiotic drug?", "paraphrased"),
("statue_of_liberty", "What is the Statue of Liberty and who gave it to the United States?", "matched"),
("statue_of_liberty", "Which giant harbor monument, a French gift dedicated in 1886, portrays a robed figure raising a torch to symbolize liberty?", "paraphrased"),
("jenner_vaccine", "Who developed the first vaccine and against which disease?", "matched"),
("jenner_vaccine", "Which 18th-century physician's cowpox-based experiment paved the way for immunology and the eventual global elimination of a deadly viral disease?", "paraphrased"),
]

assert len(PASSAGES) == 24
assert len(QUESTIONS) == 48
